micronaut:
  application:
    name: exampleAtp
  http:
    services:
      pet-health:
        url: http://localhost:8081
datasources:
  default:
    url: jdbc:oracle:thin:@mnociatp_high
    driverClassName: oracle.jdbc.OracleDriver
    username: mnocidemo
    password: ''
    schema-generate: CREATE_DROP
    dialect: ORACLE
